# -*- coding: utf-8 -*-
"""mesclador.pdf.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13tESCt95f7dIpx7uhw4YYVS7IIxmCnYa
"""

import PyPDF2
import os

merger = PyPDF2.PdfMerger()

lista_arquivos = os.listdir("arquivos")
lista_arquivos.sort()


for arquivos in lista_arquivos:
  if ".pdf" in arquivo:
    merger.append(f"arquivos/{arquivo}")


merger.write("hashtag programação")

from google.colab import drive
drive.mount('/content/drive')